//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayitDealerGlobalPayit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserDevice
    {
        public long ID { get; set; }
        public Nullable<int> AppID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> DeviceID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> isMobileVerified { get; set; }
        public Nullable<bool> isEmailVerified { get; set; }
        public string Info1 { get; set; }
        public string Info2 { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual App App { get; set; }
    }
}
