//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayitDealerGlobalPayit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppVersion
    {
        public AppVersion()
        {
            this.AppVersionConfigurations = new HashSet<AppVersionConfiguration>();
            this.TransactionsCompletes = new HashSet<TransactionsComplete>();
        }
    
        public int AppVersionID { get; set; }
        public Nullable<int> AppPlatformID { get; set; }
        public Nullable<int> AppID { get; set; }
        public string Code { get; set; }
        public string AppLink { get; set; }
        public string ShortLink { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> isMandatory { get; set; }
        public Nullable<System.DateTime> LiveDate { get; set; }
        public Nullable<double> VersionNumber { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string SecretKey { get; set; }
        public string SecureSecretKey { get; set; }
    
        public virtual ICollection<AppVersionConfiguration> AppVersionConfigurations { get; set; }
        public virtual ICollection<TransactionsComplete> TransactionsCompletes { get; set; }
    }
}
