//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayitDealerGlobalPayit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppVersionConfiguration
    {
        public int AppVersionConfigID { get; set; }
        public Nullable<int> AppVersionID { get; set; }
        public Nullable<int> ServicesAndPaymentsID { get; set; }
        public string Code { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> isTesting { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual AppVersion AppVersion { get; set; }
    }
}
