//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayitDealerGlobalPayit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryBranch
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string FacebookURL { get; set; }
        public string TwitterURL { get; set; }
        public string InstagramURL { get; set; }
        public string YoutubeURL { get; set; }
        public string FacebookAppURL { get; set; }
        public string TwitterAppURL { get; set; }
        public string InstagramAppURL { get; set; }
        public string YoutubeAppURL { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string EmailID1 { get; set; }
        public string EmailID2 { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string OtherMediaURL1 { get; set; }
        public string OtherMediaURL2 { get; set; }
    }
}
