//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayitDealerGlobalPayit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dealer()
        {
            this.Agents = new HashSet<Agent>();
            this.DealerCategoryUpdates = new HashSet<DealerCategoryUpdate>();
            this.DealerDevices = new HashSet<DealerDevice>();
            this.Sessions = new HashSet<Session>();
            this.SupportTickets = new HashSet<SupportTicket>();
            this.Tbl_Agent_Balance = new HashSet<Tbl_Agent_Balance>();
            this.Tbl_Agent_WalletBalance_History = new HashSet<Tbl_Agent_WalletBalance_History>();
            this.Tbl_Agent_WalletBalance = new HashSet<Tbl_Agent_WalletBalance>();
            this.Tbl_Dealer_Balance = new HashSet<Tbl_Dealer_Balance>();
            this.Tbl_Dealer_WalletBalance = new HashSet<Tbl_Dealer_WalletBalance>();
            this.Tbl_Dealer_WalletBalance_History = new HashSet<Tbl_Dealer_WalletBalance_History>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        public string DealerName { get; set; }
        public string Address { get; set; }
        public bool Status { get; set; }
        public System.DateTime JoinedTime { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Description { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<System.DateTime> LastPasswordChange { get; set; }
        public string DealerType { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> DealerCategoryId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agent> Agents { get; set; }
        public virtual DealerCategory DealerCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealerCategoryUpdate> DealerCategoryUpdates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealerDevice> DealerDevices { get; set; }
        public virtual Dealer Dealers1 { get; set; }
        public virtual Dealer Dealer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Sessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupportTicket> SupportTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Agent_Balance> Tbl_Agent_Balance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Agent_WalletBalance_History> Tbl_Agent_WalletBalance_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Agent_WalletBalance> Tbl_Agent_WalletBalance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Dealer_Balance> Tbl_Dealer_Balance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Dealer_WalletBalance> Tbl_Dealer_WalletBalance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Dealer_WalletBalance_History> Tbl_Dealer_WalletBalance_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
