//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayitDealerGlobalPayit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealerCategoryUpdate
    {
        public int Id { get; set; }
        public int DealerId { get; set; }
        public string DealerName { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> StartedOn { get; set; }
    
        public virtual Dealer Dealer { get; set; }
    }
}
