//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayitDealerGlobalPayit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Denomination
    {
        public int ID { get; set; }
        public Nullable<double> Amount { get; set; }
        public int Status { get; set; }
    
        public virtual Denomination Denominations1 { get; set; }
        public virtual Denomination Denomination1 { get; set; }
    }
}
