//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayitDealerGlobalPayit.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GlobalPayitEntities : DbContext
    {
        public GlobalPayitEntities()
            : base("name=GlobalPayitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppVersionConfiguration> AppVersionConfigurations { get; set; }
        public virtual DbSet<AppVersion> AppVersions { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Translation> Translations { get; set; }
        public virtual DbSet<CountryBranch> CountryBranches { get; set; }
        public virtual DbSet<TransactionsComplete> TransactionsCompletes { get; set; }
    }
}
