//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayitDealerGlobalPayit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISysWallet
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime AssignTime { get; set; }
        public int WalletItemType { get; set; }
    
        public virtual WalletItemType WalletItemType1 { get; set; }
    }
}
