//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayitDealerGlobalPayit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servvice
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string service_type { get; set; }
        public string Description { get; set; }
        public decimal Commission { get; set; }
        public int ProviderId { get; set; }
        public bool Status { get; set; }
        public Nullable<bool> showService { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> ServiceTypeID { get; set; }
    }
}
