//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayitDealerGlobalPayit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int Id { get; set; }
        public string SessionId { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public bool FromAPI { get; set; }
        public int DeviceId { get; set; }
        public int AgentId { get; set; }
        public int DealerId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Dealer Dealer { get; set; }
        public virtual Device Device { get; set; }
    }
}
