//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayitDealerGlobalPayit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportTicket
    {
        public int Id { get; set; }
        public string TicketTitle { get; set; }
        public string TicketSubject { get; set; }
        public string TicketBody { get; set; }
        public int TicketStatus { get; set; }
        public System.DateTime OpenTime { get; set; }
        public Nullable<System.DateTime> CloseTime { get; set; }
        public int DeviceId { get; set; }
        public int AgentId { get; set; }
        public int DealerId { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Dealer Dealer { get; set; }
        public virtual Device Device { get; set; }
    }
}
