//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayitDealerGlobalPayit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Balance_History
    {
        public int HistoryId { get; set; }
        public Nullable<int> BalanceType { get; set; }
        public Nullable<int> FromBalance { get; set; }
        public Nullable<int> ToBalance { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<double> Commision { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    }
}
