//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayitDealerGlobalPayit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Dealer_Balance
    {
        public int DealerBalanceId { get; set; }
        public int DealerId { get; set; }
        public int ServiceId { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<double> Commission { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Dealer Dealer { get; set; }
        public virtual DealerServiceCommision DealerServiceCommision { get; set; }
    }
}
