//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayitDealerGlobalPayit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User_Privileges
    {
        public int PrivilegeID { get; set; }
        public int MenuID { get; set; }
        public int TabID { get; set; }
        public int RoleID { get; set; }
        public bool IsParent { get; set; }
        public bool IsAdd { get; set; }
        public bool IsChangeStatus { get; set; }
        public bool IsAccessTab { get; set; }
        public bool IsProcess { get; set; }
        public bool IsReport { get; set; }
        public bool IsSummary { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Tbl_Menu_Master Tbl_Menu_Master { get; set; }
        public virtual Tbl_Tab_Master Tbl_Tab_Master { get; set; }
    }
}
