//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayitDealerGlobalPayit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Account_Balance_History
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public Nullable<double> airtime_bal { get; set; }
        public Nullable<double> mobile_money_bal { get; set; }
        public System.DateTime AssignTime { get; set; }
        public string WalletItemType { get; set; }
        public string TransactionReference { get; set; }
        public Nullable<System.DateTime> tran_date { get; set; }
        public Nullable<int> dealer_id { get; set; }
        public Nullable<int> agent_id { get; set; }
        public Nullable<int> device_id { get; set; }
        public Nullable<int> service_id { get; set; }
    }
}
