//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayitDealerGlobalPayit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.Transactions_Log = new HashSet<Transactions_Log>();
        }
    
        public int Id { get; set; }
        public System.DateTime TransactionTime { get; set; }
        public Nullable<int> DeviceId { get; set; }
        public Nullable<int> AgentId { get; set; }
        public int DealerId { get; set; }
        public int ServiceId { get; set; }
        public string FailureReason { get; set; }
        public string MobileMoneyNumber { get; set; }
        public string MobileChargeNumber { get; set; }
        public decimal Amount { get; set; }
        public Nullable<bool> IsInternetBundle { get; set; }
        public string NetworkOperator { get; set; }
        public string Status { get; set; }
        public string track_id { get; set; }
        public string type { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> AccountUserId { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Dealer Dealer { get; set; }
        public virtual Device Device { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transactions_Log> Transactions_Log { get; set; }
    }
}
