//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayitDealerGlobalPayit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionsComplete
    {
        public long ID { get; set; }
        public string Code { get; set; }
        public string CountryCode { get; set; }
        public string ReferenceID { get; set; }
        public string ResponseTrackID { get; set; }
        public string Customer { get; set; }
        public Nullable<double> Amount { get; set; }
        public string ServiceCode { get; set; }
        public string PaymentChannelCode { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.DateTime> ProcessTranDate { get; set; }
        public string ServiceReference { get; set; }
        public string PaymentReference { get; set; }
        public string UserReference { get; set; }
        public string Info1 { get; set; }
        public string Info2 { get; set; }
        public string Info3 { get; set; }
        public Nullable<bool> Status { get; set; }
        public string StatusDescription { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string AppCode { get; set; }
        public Nullable<double> PaymentAmount { get; set; }
        public string PaymentCurrencyCode { get; set; }
        public Nullable<int> ServiceConfigID { get; set; }
        public Nullable<int> ServicePaymentID { get; set; }
        public Nullable<int> PaymentConfigID { get; set; }
        public Nullable<int> AppVersionID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<int> AppVerConfigID { get; set; }
        public string IPAddress { get; set; }
        public string Device { get; set; }
    
        public virtual AppVersion AppVersion { get; set; }
    }
}
