//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayitDealerGlobalPayit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Update
    {
        public int Id { get; set; }
        public bool Force { get; set; }
        public string Version { get; set; }
        public string Description { get; set; }
        public string DownloadUrl { get; set; }
        public string Platform { get; set; }
    }
}
