//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayitDealerGlobalPayit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.Tbl_Account_Users = new HashSet<Tbl_Account_Users>();
        }
    
        public int UserId { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string company { get; set; }
        public string description { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> EntityId { get; set; }
        public int RoleID { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string DealerName { get; set; }
        public Nullable<bool> IsFirstLogin { get; set; }
        public Nullable<System.DateTime> FirstLoginDate { get; set; }
    
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Account_Users> Tbl_Account_Users { get; set; }
    }
}
